[tools]
elixir = "1.18.3-otp-27"
erlang = "27.3.4"
direnv = "2.34.0"

[env]
PORT = "4001"
ADMIN_USERNAME = "sd_admin"
ADMIN_PASSWORD = "sd_admin"
TCP_PORT = "5050"  
SWEET_DATE_API_KEY_ID = "99eccb44-2b95-489e-8445-99f47aa45262"
SWEET_DATE_API_SECRET = "test-api_secret"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DB = "sweet_date_db"