[tools]
elixir = "1.18.3-otp-27"
erlang = "27.3.4"
direnv = "2.34.0"

[env]
PORT = "4001"
ADMIN_USERNAME = "sd_admin"
ADMIN_PASSWORD = "sd_admin"
TCP_PORT = "5050"  
SWEET_DATE_API_KEY_ID = "99eccb44-2b95-489e-8445-99f47aa45262"
SWEET_DATE_API_SECRET = "test-api_secret"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DB = "sweet_date_db"
SD_REST_PORT = "4008"
SD_WEB_PORT = "4001"
SD_APP_ID = "app_7dc655cb-30ee-422f-b13a-f0a796c53879"
SD_APP_SECRET = "bgQLeeLa3Sm8rXu2zhOO9VU1SdgAB8z2SSlBHDx2KKg"